/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_Native */

#ifndef _Included_dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_Native
#define _Included_dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_Native
 * Method:    sendCtrlC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_00024Native_sendCtrlC
  (JNIEnv *, jclass);

/*
 * Class:     dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_Native
 * Method:    ignoreCtrlC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_00024Native_ignoreCtrlC
  (JNIEnv *, jclass);

/*
 * Class:     dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_Native
 * Method:    unignoreCtrlC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_00024Native_unignoreCtrlC
  (JNIEnv *, jclass);

/*
 * Class:     dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_Native
 * Method:    freeConsole
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_00024Native_freeConsole
  (JNIEnv *, jclass);

/*
 * Class:     dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_Native
 * Method:    attachConsole
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_00024Native_attachConsole
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_Native
 * Method:    getProcessId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dk_itu_coqoon_core_coqtop_WindowsConsoleUtilities_00024Native_getProcessId
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
